# ExternalSecret
# 
# Retrieve Secret from IBM Cloud Secrets Manager and generate a Secret with the values
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: externalsecret-demo-creds-01
spec:
  refreshInterval: 1m0s
  secretStoreRef:
    name: secretstore-ibm-secretsmanager
    kind: ClusterSecretStore
  target:
    name: demo-creds-01
    creationPolicy: Owner
  data:
  - secretKey: pw
    remoteRef:
      key: 'username_password/cdbc6dc4-f5f9-f53d-c58e-dffffe036b1a'
      property: 'password'
  - secretKey: id
    remoteRef:
      key: 'username_password/cdbc6dc4-f5f9-f53d-c58e-dffffe036b1a'
      property: 'username'
