# ExternalSecret
# 
# Retrieve Secret from IBM Cloud Secrets Manager and generate a Secret with the values
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: externalsecret-demo-creds-01
spec:
  backendType: ibmcloudSecretsManager
  data:
    # The guid id of the secret
    - key: 0cb00125-c5fe-056d-61be-048e4c24baf2
      name: username
      property: username
      secretType: username_password
    - key: 0cb00125-c5fe-056d-61be-048e4c24baf2
      name: password
      property: password
      secretType: username_password