# Base configuration for HashiCorp Vault example
# - service accounts and roles
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-system-a-dev
  namespace: vault-test1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-system-b-dev
  namespace: vault-test2
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: sa-system-a-dev-role-tokenreview-binding
#  namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: sa-system-a-dev
    namespace: vault-test1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: sa-system-a-dev-privileged-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: sa-system-a-dev
  namespace: vault-test1
---