apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: username-password-example
spec:
  backendType: ibmcloudSecretsManager
  data:
    # The guid id of the secret
    - key: 301be655-0c36-b231-4d08-43ffdabd938e
      name: username
      property: username
      secretType: username_password
    - key: 301be655-0c36-b231-4d08-43ffdabd938e
      name: password
      property: password
      secretType: username_password